version: '3.1'
services:
  xentral:
    container_name: xentral_app
    restart: always
    image: 'deinebaustoffe/xentral:ubuntu.18.04'
    ports:
      - '8011:80'
    links:
      - mysql
    labels:
      - "virtual.host=xentral-dev.db-ops.de"
      - "virtual.port=8011"
      - "virtual.tls-email=dev@deinebaustoffe.de"
  mysql:
    container_name: xentral_db
    restart: always
    image: 'mysql:5.7'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: xentral
      MYSQL_DATABASE: xentral
      MYSQL_USER: xentral
      MYSQL_PASSWORD: xentral
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./caddy-info:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - xentral_app